# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('full_name', models.CharField(max_length=40)),
                ('password_hash', models.TextField()),
                ('GMC_no', models.CharField(max_length=40, unique=True)),
                ('practice_no', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('REQUEST', 'request'), ('SUBMISSION', 'submission')], max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('clinician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetabolicApp.Clinician')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('password_hash', models.TextField()),
                ('DoB', models.DateField()),
                ('NHS_no', models.CharField(max_length=40, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('clinician_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MetabolicApp.Clinician')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('CHOLESTEROL', 'Fasting_cholesterol'), ('LIPIDS', 'Lipids'), ('PROLACTIN', 'Prolactin'), ('RENAL', 'Renal_Functions'), ('BLOOD', 'Blood_pressure'), ('ECG', 'ECGs'), ('BMI', 'BMI'), ('FBSUGAR', 'Fasting_blood_sugar'), ('HBA1C', 'HbA1c'), ('LIVER', 'Liver_function')], max_length=15)),
                ('test_data', models.FileField(upload_to='')),
                ('next_test', models.DateField(blank=True)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('clinician_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='MetabolicApp.Clinician')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='MetabolicApp.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='inbox',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MetabolicApp.Patient'),
        ),
    ]
