# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0002_auto_20170226_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
