# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0004_auto_20170228_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='access_token',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='access_token_created_on',
            field=models.DateTimeField(null=True),
        ),
    ]
