# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0007_auto_20170228_0619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='email',
            new_name='username',
        ),
    ]
