# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0008_auto_20170228_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(default=object, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
