# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0009_patient_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
