# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0010_remove_patient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.CharField(max_length=40),
        ),
    ]
