# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetabolicApp', '0012_auto_20170228_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
